const CryptoJS = require('crypto-js')

// Check if the entered email for signup already exists in the database:

/*
 * checkIfEmailExists variable assigned to function (only line 14) generated by ChatGPT-4 
 * 
 * @author https://chat.openai.com/
 * 
 * All content the function loop is NOT AI generated or from a website, it was created by a team member.
 */
const checkIfEmailExists = async function(email, userCollection, key, iv) {
    try {
        // Get all of the users from the 'users' collection in db using .find with empty query '{}'
        const dbUserEmails = await userCollection.find({}).project({email: 1, _id: 1}).toArray();

        // Decrypt each email, comparing each with the user entered email in sign up page
        dbUserEmails.forEach((dbEmail) => {

            const decryptedDbEmail = CryptoJS.AES.decrypt(dbEmail.email, key, { iv: iv}).toString(CryptoJS.enc.Utf8);

            // If the user entered email matches an email in the database
            if (email == decryptedDbEmail) {
                throw new Error("Entered email already exists");
            }
        });

    } catch (emailExistsError) { // If a user in the db with the same email was found
        
        // Throw the error - caught by function in signup-joi-schema.js
        throw emailExistsError;
    }
};

// Save the function in a variable to be able to export it to client side and server side
/*
 * Export the object function.
 * Generated by ChatGPT-4
 *
 * @author https://chat.openai.com/
 */
module.exports = {
    checkIfEmailExists,
};
