const content_container = document.querySelector('.content-container');
const modal = document.getElementById('modal');
const closeButton = document.querySelector('.close-button');

const modalName = document.getElementById('modal-name');
const modalDescription = document.getElementById('modal-description');
const modalPrice = document.getElementById('modal-price');
const saveButton = document.getElementById('save-button');
const cancelButton = document.getElementById('cancel-button');

const createService = document.querySelector('.create-service')
const deleteService = document.querySelector('.delete-service')

const createContainer = document.querySelector('.create-container')
const cancelButtonForCreate = document.getElementById('cancel-button-create')
const createButton = document.getElementById('create-button')

const createdPopUp = document.querySelector('#created')
const deleteButton = document.querySelector('.delete-service')
const invalid = document.querySelector('#invalid')

const deletedPopUp = document.querySelector('#deleted')
const priceInvalid = document.querySelector('#priceInvalid')
let modalId;

document.addEventListener('DOMContentLoaded', () => {
    createCards(services)
})


// Create a card that contains name, description, and price 
// The values are received from index.js
function createCards(services) {

    services.forEach((service, index) => {
        const serviceCard = document.createElement('div')
        serviceCard.classList.add('serviceCard')

        const serviceName = document.createElement('div')
        serviceName.classList.add('serviceName')

        const serviceDes = document.createElement('div')
        serviceDes.classList.add('serviceDes')

        const servicePrice = document.createElement('div')
        servicePrice.classList.add('servicePrice')


        serviceName.textContent = service.name
        serviceDes.textContent = service.description
        servicePrice.textContent = service.price

        serviceCard.addEventListener('click', () => {
            openModal(service, index);
        })

        serviceCard.appendChild(serviceName)
        serviceCard.appendChild(serviceDes)
        serviceCard.appendChild(servicePrice)

        content_container.appendChild(serviceCard)
    })
}


// 
let currentServiceIndex = null;


// This is for updating service information 
function openModal(service, index) {
    modal.style.display = 'block';
    modalName.textContent = document.querySelectorAll('.serviceName')[index].textContent
    modalDescription.textContent = document.querySelectorAll('.serviceDes')[index].textContent
    modalPrice.textContent = document.querySelectorAll('.servicePrice')[index].textContent
    currentServiceIndex = index;
    modalId = service._id

}

function closeModal() {
    modal.style.display = 'none';
}



closeButton.addEventListener('click', closeModal);
cancelButton.addEventListener('click', closeModal);

saveButton.addEventListener('click', () => {
    if (currentServiceIndex !== null) {
        const updatedService = {
            name: modalName.textContent,
            description: modalDescription.textContent,
            price: modalPrice.textContent
        };
        updateServiceCard(currentServiceIndex, updatedService);
        closeModal();

        // Generated by chat gpt 3.5
        //@author https://chat.openai.com/
        fetch('/update', {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ modalId, updatedService }),
        })
    }
});

window.addEventListener('click', (event) => {
    if (event.target === modal) {
        closeModal();
    }
});

// instead of re-creating all the cards, change the portion
function updateServiceCard(index, updatedService) {

    const card = content_container.children[index];

    console.log(card);
    card.querySelector('.serviceName').textContent = updatedService.name;
    card.querySelector('.serviceDes').textContent = updatedService.description;
    card.querySelector('.servicePrice').textContent = updatedService.price;
}

createService.addEventListener('mouseenter', function () {
    this.textContent = 'Create';
    this.classList.add('expand')
});

createService.addEventListener('mouseleave', function () {
    this.textContent = '+';
    this.classList.remove('expand')
});

deleteService.addEventListener('mouseenter', function () {
    this.textContent = 'Delete';
    this.classList.add('expand')
});

deleteService.addEventListener('mouseleave', function () {
    this.textContent = '-';
    this.classList.remove('expand')
});


function openCreateForm() {
    createContainer.style.display = 'block'
}

function closeCreateForm() {
    createContainer.style.display = 'none'
}

createService.addEventListener('click', () => {
    if (createContainer.style.display == 'block') {
        closeCreateForm()
    } else {

        openCreateForm()
    }

})

cancelButtonForCreate.addEventListener('click', () => {
    closeCreateForm()
})

// when create button is clicked, new service will be created 
//Generated by chat gpt 3.5
// @author https://chat.openai.com/
createButton.addEventListener('click', () => {
    closeCreateForm()
    const name = document.getElementById('name').value
    const description = document.getElementById('description').value
    const price = document.getElementById('price').value

    if (isNaN(parseFloat(price))) {

        priceInvalid.style.display = 'block';
        setTimeout(() => {
            priceInvalid.style.display = 'none';
        }, 1500);
        closeCreateForm()
        return
    }
    const imageFile = document.getElementById('image')

    const image = imageFile.files[0]

    const formData = new FormData();
    formData.append('name', name);
    formData.append('description', description);
    formData.append('price', price);
    formData.append('image', image); // Append the file object itself

    fetch('/create', {
        method: 'POST',
        body: formData,
    })
        .then(response => {
            if (response.status === 400) {
                invalid.style.display = 'block';
                setTimeout(() => {
                    invalid.style.display = 'none';
                }, 1500);
                return response.json().then(data => {
                    throw new Error(data.message);
                });
            } else if (response.status === 200) {
                return response.json();
            } else {

                throw new Error('Unexpected response from server');
            }
        })
        .then(data => {

            if (data.message === 'Entry created successfully.') {

                closeCreateForm();
                createdPopUp.style.display = 'block';
                setTimeout(() => {
                    createdPopUp.style.display = 'none';
                }, 1500);
                setTimeout(() => {
                    location.reload()
                }, 1000);

            } else {

                console.error('Unexpected message from server:', data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
        });


})

deleteButton.addEventListener('click', () => {
    closeCreateForm()
})

let deleteButtonClicked = false;

deleteService.addEventListener('click', () => {
    if (!deleteButtonClicked) {
        const cards = document.querySelectorAll('.serviceCard');
        cards.forEach((card) => {
            const deleteButtonForEntry = document.createElement('div');
            deleteButtonForEntry.classList.add('deleteButtonForEntry')
            deleteButtonForEntry.textContent = 'Delete'
            deleteButtonForEntry.addEventListener('click', () => {
                const previousCard = deleteButtonForEntry.previousElementSibling;

                const cardName = previousCard.querySelector('.serviceName').textContent
                fetch('/delete', {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({ cardName }),
                })
                    .then(response => response.json())
                    .then(data => {
                        console.log(data.message);
                        deletedPopUp.style.display = 'block';
                        setTimeout(() => {
                            deletedPopUp.style.display = 'none';
                        }, 1500);
                        setTimeout(() => {
                            location.reload()
                        }, 1000);
                    })
            })
            card.insertAdjacentElement('afterend', deleteButtonForEntry);
            deleteButtonClicked = true;
        });
    } else {
        document.querySelectorAll('.deleteButtonForEntry').forEach(button => {
            button.remove()
        })
        deleteButtonClicked = false;
    }

})